# Generated by Django 4.0.4 on 2023-10-19 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_remove_team_members_teammember_teammanager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammanager',
            name='team_members',
        ),
        migrations.AddField(
            model_name='teammanager',
            name='team_members',
            field=models.ManyToManyField(to='team.teammember'),
        ),
    ]
