# Generated by Django 4.0.4 on 2023-10-18 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profession',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
