# Generated by Django 4.0.4 on 2023-10-18 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_profession'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='skills',
            field=models.CharField(blank=True, max_length=510, null=True),
        ),
    ]
